name: trajectory-prediction
phase: mrm

target:
  _target_: src.model.trainer_mrm.Trainer
  lane_dim: 2
  dim: 128
  encoder_depth: 4
  num_heads: 8
  lr: ${lr}
  weight_decay: ${weight_decay}
  epochs: ${epochs}
  warmup_epochs: ${warmup_epochs}
